--- 
- hosts: 172.31.26.171
  become: yes
  tasks: 
    - include_tasks: myfile.yml
     
    - name: install webserver
      apt: 
       name: apache2
       state: present 

    - name: copy index file into ansible nodes side
      template: 
        src: index.j2
        dest: /var/www/html/index.html