---
- hosts: 172.31.12.112
  become: yes
  tasks:
   - name: i want to install git,tree,wget
     apt:
       name: "{{item}}"
       state: present 
     loop:
        - git 
        - tree 
        - wget  