---
- hosts: 172.31.26.171
  become: yes
  tasks:
     name: i want to install git,tree.wget
     apt:
       name: "{{ item }}"
       state: present 
     loops:
        - git 
        - tree 
        - wget  